// manifest-test.js — SECTION-SURVIVAL TRIPWIRE (v0.9.49)
// Every UI string the app rendered at v0.9.48 must still exist in source.
// A restyle that deletes a card, label, button, or state message turns this red.
// Match-before-replace, enforced: edit styles, never remove surface.
const __FCROOT = require("path").resolve(__dirname, "..", "..");
const SRC = require("fs").readFileSync(__FCROOT + "/src/App.jsx", "utf8");
const MANIFEST = [
 "$ price",
 "1 easy set, no load",
 "6 Pack Promise",
 "A rate needs at least 4 weigh-ins across 12+ days.",
 "Active loss",
 "Add another allergy (e.g. mustard, avocado)",
 "Add photos to build a visual transformation timeline.",
 "Anthropic key (sk-ant-…)",
 "Approaching goal",
 "Ask about this menu… (swaps, carbs, drinks)",
 "Ask your coach…",
 "Auto-syncing",
 "NOT SYNCED",
 "Back to current plan",
 "Backup (JSON)",
 "Barcode number",
 "Body Forecaster",
 "Calories",
 "Caster",
 "Center the shelf item's barcode in the box",
 "Check these before saving",
 "Clear synced data",
 "Core runs as a circuit",
 "Cutting",
 "DOORDASH",
 "DOSE-SYNCED PREP",
 "Day & units",
 "Discard",
 "Dose due today — log it once taken",
 "Equipment you actually have",
 "Estimated med level",
 "Export PDF report — for your prescriber",
 "FatSecret Client ID — optional",
 "FatSecret Client Secret — optional",
 "Filtering out:",
 "Find Health Samples",
 "ForkCaster",
 "ForkCaster report",
 "Format Date",
 "GRUBHUB",
 "Get Contents of URL",
 "Goal ETA: needs a downward trend to project.",
 "Goal preview",
 "Google AI (Gemini) key — for goal body simulation",
 "Google Places key (AIza…) — optional",
 "Hide this card",
 "How ForkCaster gets its numbers",
 "Images on your node",
 "Investigational (Phase 3, not FDA-approved).",
 "L/R are",
 "Lifting is the half of muscle protection food can't do",
 "Log your first weight below to start the trend.",
 "Maintain",
 "Maintenance / off-ramp",
 "Map & nearby",
 "Milestone",
 "Minimum hold before a checkpoint",
 "Muscle gain",
 "My preset",
 "No food spots near you",
 "No matches — try fewer words.",
 "No photo yet — yours goes here",
 "No readable numbers yet",
 "No routine yet — open",
 "One thing only you can answer.",
 "Or search food by name (e.g. grilled chicken breast)",
 "Orforglipron",
 "Plan settings",
 "Point at any food barcode — or type it below",
 "Point at the shelf item's barcode — or type it below",
 "Prefer one coach's channel for form videos (optional)",
 "Progress",
 "Protein",
 "Raise protein +15g/day",
 "Ramp-up",
 "Reset all data — start fresh",
 "Rest day — next session is on the Week view.",
 "Resting Heart Rate",
 "Restore",
 "Restore a previous save",
 "Retatrutide",
 "Routine",
 "Rungs (mg, separated by spaces or commas)",
 "Save keys",
 "Save protocol",
 "Scan another",
 "Scan or log food",
 "Scan with camera",
 "Search",
 "Search this area",
 "Semaglutide",
 "Semaglutide (oral)",
 "Settings",
 "Shortcuts",
 "Show snapshots",
 "Show the Apple Health card again",
 "Sleep Analysis",
 "Start session",
 "Stored privately on your node.",
 "Sweep orphaned images",
 "Symptom patterns",
 "Tap any number above to log intake by hand",
 "Test AI key",
 "This week",
 "Those meals averaged",
 "Tirzepatide",
 "Tolerability flags right now:",
 "Trim calories −125/day",
 "Uber Eats",
 "Waiting for sleep data. Add the",
 "Waiting for your first logged dose",
 "Wearables",
 "Why this meal today:",
 "You're at the top of the ladder —",
 "YouTube Data API key (optional) — short exercise demo clips",
 "Your best body is in the",
 "You’re at (or past) goal — maintenance mode.",
 "app — no third-party apps, no cloud:",
 "bpm today",
 "burned today",
 "calories cross-checked against macros",
 "carbs to go",
 "cardio",
 "consolidated across all meals",
 "fat budget left",
 "fiber to go",
 "followed a high-fat meal",
 "forecast",
 "is the maintenance dose. Holding here is the plan.",
 "lean mass holding",
 "lean mass to protect",
 "leave blank — searches all of YouTube",
 "of your nausea flares",
 "protein",
 "protein to go",
 "quick && (",
 "re-answer",
 "since start",
 "tap to retry",
 "this day",
 "to goal weight",
 "water to go",
 "your left",
 "your right"
];
let pass=0, fail=0;
for (const s of MANIFEST) {
  if (SRC.includes(s)) pass++;
  else { fail++; console.log("  FAIL: UI string missing from App.jsx: " + JSON.stringify(s)); }
}
console.log(`\nMANIFEST: ${pass} passed, ${fail} failed`);
if (fail) process.exit(1);
